students = [
    {
        "enrollment_no": "123456",
        "password": "password123",
        "username": "john_doe",
        "email": "john.doe@example.com",
        "section": "A",
        "branch": "Computer Science",
        "academic_year": "2024",
        "gender": "Male",
        "phone_no": "1234567890",
        "dob": "2000-01-01",
        "profile_pic": "profile.jpg",
        "parent_name": "Jane Doe",
        "parent_no": "9876543210",
        "current_address": "123 Main St, City"
    },
    {
        "enrollment_no": "234567",
        "password": "password234",
        "username": "jane_smith",
        "email": "jane.smith@example.com",
        "section": "B",
        "branch": "Electrical Engineering",
        "academic_year": "2023",
        "gender": "Female",
        "phone_no": "9876543210",
        "dob": "2001-05-15",
        "profile_pic": "profile2.jpg",
        "parent_name": "John Smith",
        "parent_no": "1234567890",
        "current_address": "456 Elm St, Town"
    },
    {
        "enrollment_no": "345678",
        "password": "password345",
        "username": "sam_wilson",
        "email": "sam.wilson@example.com",
        "section": "C",
        "branch": "Mechanical Engineering",
        "academic_year": "2025",
        "gender": "Male",
        "phone_no": "8765432109",
        "dob": "2002-09-30",
        "profile_pic": "profile3.jpg",
        "parent_name": "Sarah Wilson",
        "parent_no": "9876543210",
        "current_address": "789 Oak St, Village"
    },
    {
        "enrollment_no": "456789",
        "password": "password456",
        "username": "emily_brown",
        "email": "emily.brown@example.com",
        "section": "A",
        "branch": "Civil Engineering",
        "academic_year": "2024",
        "gender": "Female",
        "phone_no": "7654321098",
        "dob": "2000-12-20",
        "profile_pic": "profile4.jpg",
        "parent_name": "Michael Brown",
        "parent_no": "8765432109",
        "current_address": "987 Pine St, Hamlet"
    },
    {
        "enrollment_no": "567890",
        "password": "password567",
        "username": "alex_jones",
        "email": "alex.jones@example.com",
        "section": "B",
        "branch": "Chemical Engineering",
        "academic_year": "2023",
        "gender": "Male",
        "phone_no": "6543210987",
        "dob": "2001-08-10",
        "profile_pic": "profile5.jpg",
        "parent_name": "Michelle Jones",
        "parent_no": "7654321098",
        "current_address": "654 Maple St, Borough"
    },
    {
        "enrollment_no": "678901",
        "password": "password678",
        "username": "olivia_garcia",
        "email": "olivia.garcia@example.com",
        "section": "C",
        "branch": "Computer Science",
        "academic_year": "2025",
        "gender": "Female",
        "phone_no": "5432109876",
        "dob": "2002-03-25",
        "profile_pic": "profile6.jpg",
        "parent_name": "David Garcia",
        "parent_no": "6543210987",
        "current_address": "321 Cedar St, City"
    },
    {
        "enrollment_no": "789012",
        "password": "password789",
        "username": "noah_rodriguez",
        "email": "noah.rodriguez@example.com",
        "section": "A",
        "branch": "Electrical Engineering",
        "academic_year": "2024",
        "gender": "Male",
        "phone_no": "4321098765",
        "dob": "2000-07-05",
        "profile_pic": "profile7.jpg",
        "parent_name": "Sophia Rodriguez",
        "parent_no": "5432109876",
        "current_address": "456 Walnut St, Town"
    },
    {
        "enrollment_no": "890123",
        "password": "password890",
        "username": "mia_martinez",
        "email": "mia.martinez@example.com",
        "section": "B",
        "branch": "Mechanical Engineering",
        "academic_year": "2023",
        "gender": "Female",
        "phone_no": "3210987654",
        "dob": "2001-04-15",
        "profile_pic": "profile8.jpg",
        "parent_name": "Daniel Martinez",
        "parent_no": "4321098765",
        "current_address": "567 Cherry St, Village"
    },
    {
        "enrollment_no": "901234",
        "password": "password901",
        "username": "ethan_hernandez",
        "email": "ethan.hernandez@example.com",
        "section": "C",
        "branch": "Civil Engineering",
        "academic_year": "2025",
        "gender": "Male",
        "phone_no": "2109876543",
        "dob": "2002-11-20",
        "profile_pic": "profile9.jpg",
        "parent_name": "Olivia Hernandez",
        "parent_no": "3210987654",
        "current_address": "789 Pine St, Hamlet"
    },
    {
        "enrollment_no": "012345",
        "password": "password012",
        "username": "ava_lopez",
        "email": "ava.lopez@example.com",
        "section": "A",
        "branch": "Chemical Engineering",
        "academic_year": "2024",
        "gender": "Female",
        "phone_no": "1098765432",
        "dob": "2000-02-10",
        "profile_pic": "profile10.jpg",
        "parent_name": "Liam Lopez",
        "parent_no": "2109876543",
        "current_address": "890 Oak St, Borough"
    }
]


